[package]
name = "gixor"
readme = "README.md"
description = "An API for managing .gitignore files."
version = "0.4.3"
edition = "2024"
license-file = "LICENSE"
authors = [ "Haruaki Tamada" ]
repository = "https://github.com/tamada/gixor"
homepage = "https://tamada.github.io/gixor/"
categories = [ "command-line-utilities", "configuration", "development-tools" ]
keywords = [ "cli", "gitignore", "gitignore-generator", "git", "shell", "gitignore-files", "gitignore-templates" ]

[features]
default = []
uselibgit = [ "git2" ]
usegix  = [ "gix" ]

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
clap_complete = "4.5.44"
env_logger = "0.11.6"
dirs = "6.0.0"
hex = "0.4.3"
ignore = "0.4.23"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
gix = { version = "0.76.0", features = [ "blocking-http-transport-reqwest-rust-tls", "blocking-network-client", "merge", "tree-editor" ], optional = true }
git2 = { version = "0.20.3", optional = true }

[dev-dependencies]
tempfile = "3.10.1"
