name: build_products
on:
  push:
    branches: 
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - name: Setup for Linux
        if: matrix.os == 'ubuntu-latest'
        run:
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
  
      - name: Setup for Windows (aarch64 (amd64))
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run:
          pacman -Syu --noconfirm mingw-w64-clang-aarch64-openssl

      - name: Setup for macOS
        if: matrix.os == 'macos-latest'
        run:
          brew install openssl@3
        
      - name: Checkout project
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      
      - uses: extractions/setup-just@v2

      - name: Build and calculate coverages
        run:
          just test

      # The coverage file (coverage.lcov) is generated by cargo test 
      # which is defined in Makefile.toml
      - name: Send Coverage to Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.os == 'ubuntu-latest'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: target/coverage.lcov 
