name: publish_site_release_assets
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  setup:
    runs-on: ubuntu-latest
    # ブランチ名が release/v から始まる場合のみに実行する．
    # プルリクエストがマージされた場合のみに実行する．
    if: startsWith(github.head_ref, 'release/v') && github.event.pull_request.merged == true
    outputs:
      appname: gixor
      tag: ${{ steps.vars.outputs.tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Git Tag name
        id: vars
        run: |
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF (${GITHUB_HEAD_REF##*/v})"
          echo "tag=${GITHUB_HEAD_REF##*/v}" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.vars.outputs.tag }}
          name: Release v${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false

  publish:
    runs-on: ${{ matrix.os }}
    needs: setup
    outputs:
      appname: ${{ needs.setup.outputs.appname }}
      tag: ${{ needs.setup.outputs.tag }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            artifact_name: ${{ needs.setup.outputs.appname }}
            asset_name: ${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}_linux_amd64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            artifact_name: ${{ needs.setup.outputs.appname }}
            asset_name: ${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}_linux_arm64
          # - os: windows-latest
          #   target: aarch64-pc-windows-gnullvm
          #   artifact_name: ${{ needs.setup.outputs.appname }}.exe
          #   asset_name: ${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}_windows_amd64
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            artifact_name: ${{ needs.setup.outputs.appname }}.exe
            asset_name: ${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}_windows_arm64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ${{ needs.setup.outputs.appname }}
            asset_name: ${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}_darwin_amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ${{ needs.setup.outputs.appname }}
            asset_name: ${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}_darwin_arm64

    steps:
      # initialization
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup variables
        id: vars
        shell: bash
        run: |
          DIR=$(echo "${{ needs.setup.outputs.appname }}-${{ needs.setup.outputs.tag }}")
          echo "dir=$DIR" >> $GITHUB_OUTPUT
  
      # - name: Cache cargo registry
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cargo/registry
      #     key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}        

      - name: Setup
        run: rustup update stable
      
      - name: Setup for Linux
        if: matrix.os == 'ubuntu-20.04'
        run:
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'
  
      - name: Setup for Windows (x86_64 (arm64))
        if: matrix.os == 'windows-latest' && contains(matrix.target, 'x86_64')
        shell: msys2 {0}
        run:
          pacman -S mingw-w64-x86_64-openssl

      - name: Setup for Windows (aarch64 (amd64))
        if: matrix.os == 'windows-latest' && contains(matrix.target, 'aarch')
        shell: msys2 {0}
        run:
          pacman -S mingw-w64-clang-aarch64-openssl

      - name: Setup for macOS
        if: matrix.os == 'macos-latest'
        run:
          brew install openssl@3

      - name: Build
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}

      # publish release
      - name: Create release file
        shell: bash
        run: |
          DIR=${{ steps.vars.outputs.dir }}
          DIST=${{ matrix.target }}
          mkdir -p dist/$DIST/$DIR
          # cp -r site/public dist/$DIST/$DIR/docs
          cp -r README.md LICENSE assets dist/$DIST/$DIR
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }}-cli dist/$DIST/$DIR/${{ matrix.artifact_name }}
          tar cvfz dist/${{ matrix.asset_name }}.tar.gz -C dist/$DIST $DIR
        
      - name: Upload release assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: dist/${{ matrix.asset_name }}.tar.gz
          asset_name: ${{ matrix.asset_name }}.tar.gz
          asset_content_type: application/x-gzip
          upload_url: ${{ needs.setup.outputs.upload_url }}

  docker:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # ${{ github.repository }} = tamada/totebag
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short
            type=raw,value=${{ needs.publish.outputs.tag }}

      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository}}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
